x1=123
y1=43.23
a1=(4-1j)
b1="How are you?"
c1=True
n=""
print("is",x1,"an instance of int?:",isinstance(x1,int),sep=" ")
print("is",y1,"an instance of bool?:",isinstance(y1,int),sep=" ")
print("is",a1,"an instance of complex?:",isinstance(a1,complex),sep=" ")
print("is",b1,"an instance of bool?:",isinstance(b1,bool),sep=" ")
print("is",c1,"an instance of float?:",isinstance(c1,int),sep=" ")